#!/bin/bash

# Get salt repo key
wget -O - https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -

# Add salt repo 
sudo echo "deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main" > /etc/apt/sources.list.d/saltstack.list

# apt update
sudo apt-get update

# Install salt minion
sudo apt-get -y install salt-master

# Salt minion service restart
sudo /etc/init.d/salt-master restart